name: drupal10
recipe: drupal10
config:
  database: mariadb:10.4
  php: '8.1'
  webroot: web
  xdebug: true
  composer_version: "2.4.2"

proxy:
  appserver:
    - drupal10.lndo.site
  mailhog:
    - mailhog.drupal10.lndo.site
  node:
    - bs.drupal10.lndo.site:3000


services:

  #  Container server
  appserver:
    xdebug: true
    type: php:8.1
    overrides:
      environment:
        PHP_IDE_CONFIG: "serverName=appserver"
    build_as_root:
      - rm -f /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && /etc/init.d/apache2 reload

  # Container databases
  database:
    portforward: 3307

  # Container Node pour la compilations des assests css/js
  node:
    type: node:18
    ssl: true
    build:
      - echo 'NodeJS container is up and running'
    overrides:
      ports:
        - '3000'
    scanner: false

  # Container Mailhog
  mailhog:
    type: mailhog
    hogfrom:
      - appserver

# Exemple de commande pour le tooling
tooling:
  yarn:
    service: node
  phpcs:
    service: appserver
    cmd: "phpcs --standard=Drupal,DrupalPractice"
    description: Run phpcs Drupal Coding Standards against a given file or directory.
  phpcbf:
    service: appserver
    cmd: "phpcbf --standard=Drupal"
    description: Automatically fix Drupal coding standards suggestions.

  xdebug-on:
    service: appserver
    description: Enable xdebug for nginx.
    cmd: rm -f /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && docker-php-ext-enable xdebug && /etc/init.d/apache2 reload && echo "Xdebug enabled"
    user: root

  xdebug-off:
    service: appserver
    description: Disable xdebug for nginx.
    cmd: rm -f /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && /etc/init.d/apache2 reload && echo "Xdebug disabled"
    user: root
